// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ServiciosPublicitarios.Entities.Entities
{
    public partial class tbFacturaDetalle
    {
        public int fdet_Id { get; set; }
        public int fact_Id { get; set; }
        public int serv_Id { get; set; }
        public int fdet_Cantidad { get; set; }
        public int fdet_UsuCreacion { get; set; }
        public DateTime fdet_FechaCreacion { get; set; }
        public int? fdet_UsuModificacion { get; set; }
        public DateTime? fdet_FechaModificacion { get; set; }
        public bool? fdet_Estado { get; set; }

        public virtual tbFacturas fact { get; set; }
        public virtual tbUsuarios fdet_UsuCreacionNavigation { get; set; }
        public virtual tbUsuarios fdet_UsuModificacionNavigation { get; set; }
        public virtual tbServicios serv { get; set; }
    }
}