// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ServiciosPublicitarios.Entities.Entities
{
    public partial class tbInsumosPorServicios
    {
        public int inse_Id { get; set; }
        public int? serv_Id { get; set; }
        public int? insu_Id { get; set; }
        public int inse_UsuCreacion { get; set; }
        public DateTime inse_FechaCreacion { get; set; }
        public int? inse_UsuModificacion { get; set; }
        public DateTime? inse_FechaModificacion { get; set; }
        public bool? inse_Estado { get; set; }

        public virtual tbUsuarios inse_UsuCreacionNavigation { get; set; }
        public virtual tbUsuarios inse_UsuModificacionNavigation { get; set; }
        public virtual tbInsumos insu { get; set; }
        public virtual tbServicios serv { get; set; }
    }
}