// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ServiciosPublicitarios.Entities.Entities
{
    public partial class tbServicios
    {
        public tbServicios()
        {
            tbFacturaDetalle = new HashSet<tbFacturaDetalle>();
            tbInsumosPorServicios = new HashSet<tbInsumosPorServicios>();
        }

        public int serv_Id { get; set; }
        public string serv_Nombre { get; set; }
        public decimal? serv_Precio { get; set; }
        public int serv_UsuCreacion { get; set; }
        public DateTime serv_FechaCreacion { get; set; }
        public int? serv_UsuModificacion { get; set; }
        public DateTime? serv_FechaModificacion { get; set; }
        public bool? serv_Estado { get; set; }

        public virtual tbUsuarios serv_UsuCreacionNavigation { get; set; }
        public virtual tbUsuarios serv_UsuModificacionNavigation { get; set; }
        public virtual ICollection<tbFacturaDetalle> tbFacturaDetalle { get; set; }
        public virtual ICollection<tbInsumosPorServicios> tbInsumosPorServicios { get; set; }
    }
}