// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ServiciosPublicitarios.Entities.Entities
{
    public partial class tbUsuarios
    {
        public tbUsuarios()
        {
            Inverseuser_UsuCreacionNavigation = new HashSet<tbUsuarios>();
            Inverseuser_UsuModificacionNavigation = new HashSet<tbUsuarios>();
            tbCargoscarg_UsuCreacionNavigation = new HashSet<tbCargos>();
            tbCargoscarg_UsuModificacionNavigation = new HashSet<tbCargos>();
            tbCategoriascate_UsuCreacionNavigation = new HashSet<tbCategorias>();
            tbCategoriascate_UsuModificacionNavigation = new HashSet<tbCategorias>();
            tbClientesclie_UsuCreacionNavigation = new HashSet<tbClientes>();
            tbClientesclie_UsuModificacionNavigation = new HashSet<tbClientes>();
            tbDepartamentosdepa_UsuCreacionNavigation = new HashSet<tbDepartamentos>();
            tbDepartamentosdepa_UsuModificacionNavigation = new HashSet<tbDepartamentos>();
            tbEmpleadosempe_UsuCreacionNavigation = new HashSet<tbEmpleados>();
            tbEmpleadosempe_UsuModificacionNavigation = new HashSet<tbEmpleados>();
            tbEstadosCivileseciv_UsuCreacionNavigation = new HashSet<tbEstadosCiviles>();
            tbEstadosCivileseciv_UsuModificacionNavigation = new HashSet<tbEstadosCiviles>();
            tbFacturaDetallefdet_UsuCreacionNavigation = new HashSet<tbFacturaDetalle>();
            tbFacturaDetallefdet_UsuModificacionNavigation = new HashSet<tbFacturaDetalle>();
            tbFacturasfact_UsuCreacionNavigation = new HashSet<tbFacturas>();
            tbFacturasfact_UsuModificacionNavigation = new HashSet<tbFacturas>();
            tbInsumosPorServiciosinse_UsuCreacionNavigation = new HashSet<tbInsumosPorServicios>();
            tbInsumosPorServiciosinse_UsuModificacionNavigation = new HashSet<tbInsumosPorServicios>();
            tbInsumosinsu_UsuCreacionNavigation = new HashSet<tbInsumos>();
            tbInsumosinsu_UsuModificacionNavigation = new HashSet<tbInsumos>();
            tbMetodosdePagometo_UsuCreacionNavigation = new HashSet<tbMetodosdePago>();
            tbMetodosdePagometo_UsuModificacionNavigation = new HashSet<tbMetodosdePago>();
            tbMunicipiosmuni_UsuCreacionNavigation = new HashSet<tbMunicipios>();
            tbMunicipiosmuni_UsuModificacionNavigation = new HashSet<tbMunicipios>();
            tbPantallasPorRolesprol_UsuCreacionNavigation = new HashSet<tbPantallasPorRoles>();
            tbPantallasPorRolesprol_UsuModificacionNavigation = new HashSet<tbPantallasPorRoles>();
            tbProveedoresprov_UsuCreacionNavigation = new HashSet<tbProveedores>();
            tbProveedoresprov_UsuModificacionNavigation = new HashSet<tbProveedores>();
            tbRolesrole_UsuCreacionNavigation = new HashSet<tbRoles>();
            tbRolesrole_UsuModificacionNavigation = new HashSet<tbRoles>();
            tbServiciosserv_UsuCreacionNavigation = new HashSet<tbServicios>();
            tbServiciosserv_UsuModificacionNavigation = new HashSet<tbServicios>();
            tbSucursalessucu_UsuCreacionNavigation = new HashSet<tbSucursales>();
            tbSucursalessucu_UsuModificacionNavigation = new HashSet<tbSucursales>();
        }

        public int user_Id { get; set; }
        public string user_NombreUsuario { get; set; }
        public string user_Contrasena { get; set; }
        public bool? user_EsAdmin { get; set; }
        public int? role_Id { get; set; }
        public int? empe_Id { get; set; }
        public int user_UsuCreacion { get; set; }
        public DateTime user_FechaCreacion { get; set; }
        public int? user_UsuModificacion { get; set; }
        public DateTime? user_FechaModificacion { get; set; }
        public bool? user_Estado { get; set; }

        public virtual tbEmpleados empe { get; set; }
        public virtual tbRoles role { get; set; }
        public virtual tbUsuarios user_UsuCreacionNavigation { get; set; }
        public virtual tbUsuarios user_UsuModificacionNavigation { get; set; }
        public virtual ICollection<tbUsuarios> Inverseuser_UsuCreacionNavigation { get; set; }
        public virtual ICollection<tbUsuarios> Inverseuser_UsuModificacionNavigation { get; set; }
        public virtual ICollection<tbCargos> tbCargoscarg_UsuCreacionNavigation { get; set; }
        public virtual ICollection<tbCargos> tbCargoscarg_UsuModificacionNavigation { get; set; }
        public virtual ICollection<tbCategorias> tbCategoriascate_UsuCreacionNavigation { get; set; }
        public virtual ICollection<tbCategorias> tbCategoriascate_UsuModificacionNavigation { get; set; }
        public virtual ICollection<tbClientes> tbClientesclie_UsuCreacionNavigation { get; set; }
        public virtual ICollection<tbClientes> tbClientesclie_UsuModificacionNavigation { get; set; }
        public virtual ICollection<tbDepartamentos> tbDepartamentosdepa_UsuCreacionNavigation { get; set; }
        public virtual ICollection<tbDepartamentos> tbDepartamentosdepa_UsuModificacionNavigation { get; set; }
        public virtual ICollection<tbEmpleados> tbEmpleadosempe_UsuCreacionNavigation { get; set; }
        public virtual ICollection<tbEmpleados> tbEmpleadosempe_UsuModificacionNavigation { get; set; }
        public virtual ICollection<tbEstadosCiviles> tbEstadosCivileseciv_UsuCreacionNavigation { get; set; }
        public virtual ICollection<tbEstadosCiviles> tbEstadosCivileseciv_UsuModificacionNavigation { get; set; }
        public virtual ICollection<tbFacturaDetalle> tbFacturaDetallefdet_UsuCreacionNavigation { get; set; }
        public virtual ICollection<tbFacturaDetalle> tbFacturaDetallefdet_UsuModificacionNavigation { get; set; }
        public virtual ICollection<tbFacturas> tbFacturasfact_UsuCreacionNavigation { get; set; }
        public virtual ICollection<tbFacturas> tbFacturasfact_UsuModificacionNavigation { get; set; }
        public virtual ICollection<tbInsumosPorServicios> tbInsumosPorServiciosinse_UsuCreacionNavigation { get; set; }
        public virtual ICollection<tbInsumosPorServicios> tbInsumosPorServiciosinse_UsuModificacionNavigation { get; set; }
        public virtual ICollection<tbInsumos> tbInsumosinsu_UsuCreacionNavigation { get; set; }
        public virtual ICollection<tbInsumos> tbInsumosinsu_UsuModificacionNavigation { get; set; }
        public virtual ICollection<tbMetodosdePago> tbMetodosdePagometo_UsuCreacionNavigation { get; set; }
        public virtual ICollection<tbMetodosdePago> tbMetodosdePagometo_UsuModificacionNavigation { get; set; }
        public virtual ICollection<tbMunicipios> tbMunicipiosmuni_UsuCreacionNavigation { get; set; }
        public virtual ICollection<tbMunicipios> tbMunicipiosmuni_UsuModificacionNavigation { get; set; }
        public virtual ICollection<tbPantallasPorRoles> tbPantallasPorRolesprol_UsuCreacionNavigation { get; set; }
        public virtual ICollection<tbPantallasPorRoles> tbPantallasPorRolesprol_UsuModificacionNavigation { get; set; }
        public virtual ICollection<tbProveedores> tbProveedoresprov_UsuCreacionNavigation { get; set; }
        public virtual ICollection<tbProveedores> tbProveedoresprov_UsuModificacionNavigation { get; set; }
        public virtual ICollection<tbRoles> tbRolesrole_UsuCreacionNavigation { get; set; }
        public virtual ICollection<tbRoles> tbRolesrole_UsuModificacionNavigation { get; set; }
        public virtual ICollection<tbServicios> tbServiciosserv_UsuCreacionNavigation { get; set; }
        public virtual ICollection<tbServicios> tbServiciosserv_UsuModificacionNavigation { get; set; }
        public virtual ICollection<tbSucursales> tbSucursalessucu_UsuCreacionNavigation { get; set; }
        public virtual ICollection<tbSucursales> tbSucursalessucu_UsuModificacionNavigation { get; set; }
    }
}