// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ServiciosPublicitarios.Entities.Entities
{
    public partial class VW_tbInsumos
    {
        public int insu_Id { get; set; }
        public string insu_Nombre { get; set; }
        public int? cate_Id { get; set; }
        public string cate_Descripcion { get; set; }
        public decimal? insu_Precio { get; set; }
        public int? prov_Id { get; set; }
        public string prov_Nombre { get; set; }
        public int insu_UsuCreacion { get; set; }
        public string user_Creacion { get; set; }
        public DateTime insu_FechaCreacion { get; set; }
        public int? insu_UsuModificacion { get; set; }
        public string user_Modificacion { get; set; }
        public DateTime? insu_FechaModificacion { get; set; }
        public bool insu_Estado { get; set; }
    }
}