// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace ServiciosPublicitarios.Entities.Entities
{
    public partial class VW_tbProveedores
    {
        public int prov_Id { get; set; }
        public string prov_Nombre { get; set; }
        public int? muni_Id { get; set; }
        public string muni_Codigo { get; set; }
        public string muni_Nombre { get; set; }
        public int depa_Id { get; set; }
        public string depa_Codigo { get; set; }
        public string depa_Nombre { get; set; }
        public string prov_Direccion { get; set; }
        public string prov_Correo { get; set; }
        public int prov_UsuCreacion { get; set; }
        public string user_Creacion { get; set; }
        public DateTime prov_FechaCreacion { get; set; }
        public int? prov_UsuModificacion { get; set; }
        public string user_Modificacion { get; set; }
        public DateTime? prov_FechaModificacion { get; set; }
        public bool prov_Estado { get; set; }
    }
}